### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by benallfree** [tigrisdata/geesefs#1]
Hello, I had a few questions about the status of this project.

1. Is it being maintained? I see they're at 0.42.3 but this was last sync'd at 0.42.0.
2. I noticed it's not a fork in the github sense, even though the Tigris docs call it a fork. Is there a reason it's not linked to the upstream on github?

**Comment by ovaistariq** [comment]
👋 Originally, the repo was private and since GitHub doesn't allow forks to be private it doesn't show up as a fork even after it has been made public. Probably should have started as a public repo in the first place. 

I would add that, though it started off as a fork, it is most likely going to deviate as we make changes not only to optimize it for Tigris but to present it as a filesystem with a global namespace similar to how the buckets are in Tigris.

**Comment by ovaistariq** [comment]
And yes it's being maintained.

**Comment by benallfree** [comment]
Thank you for the info :)
